=== mtconnect/standard_doc_generator/schema_dev/version_1.5/dataset.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:mtconnect.org:MTConnectStreams:1.5" xmlns:mt="urn:mtconnect.org:MTConnectStreams:1.5" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" targetNamespace="urn:mtconnect.org:MTConnectStreams:1.5" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:complexType name="SamplesType">
    <xs:annotation>
      <xs:documentation>
        A collection of samples for this component
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element ref="Sample" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Samples" type="SamplesType"/>
  <xs:attributeGroup name="ObservationType">
    <xs:attribute name="sequence" type="xs:integer" use="required"/>
    <xs:attribute name="timestamp" type="xs:dateTime" use="required"/>
  </xs:attributeGroup>
  <xs:simpleType name="UnavailableType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="UNAVAILABLE"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="SampleType" mixed="true">
    <xs:attributeGroup ref="ObservationType"/>
  </xs:complexType>
  <xs:element name="Sample" type="SampleType">
    <xs:annotation>
      <xs:documentation>
        An abstract sample
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="EntryType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="key" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VariableDataSetType" mixed="true">
    <xs:complexContent mixed="true">
      <xs:extension base="SampleType">
        <xs:sequence>
          <xs:element name="Entry" type="EntryType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="count" type="xs:integer"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:simpleType name="DataSetType">
    <xs:restriction base="xs:string">
      <xs:pattern value="([^ =]+=(&quot;(([^&quot;\\]*)(\\.)?)*&quot;|\{(([^}\\]*)(\\.)?)*\}|'(([^'\\]*)(\\.)?)*'|[^ ]+)[ ]*)*" />            
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="VariableDataSet" type="VariableDataSetType" substitutionGroup="Sample"/>
  <xs:complexType name="VariableFormatType" mixed="true">
    <xs:simpleContent>
      <xs:restriction base="SampleType">
        <xs:simpleType>
          <xs:union memberTypes="DataSetType UnavailableType" />
        </xs:simpleType>
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>
  <xs:element name="Variable" type="VariableFormatType" substitutionGroup="Sample"/>
</xs:schema>

=== mtconnect/standard_doc_generator/schema_dev/version_1.5/dataset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2018 rel. 2 sp1 (x64) (http://www.altova.com)-->
<mt:Samples xmlns:mt="urn:mtconnect.org:MTConnectStreams:1.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mtconnect.org:MTConnectStreams:1.5 dataset.xsd">
  <mt:VariableDataSet sequence="12344" timestamp="2019-01-01T20:00:00Z">
    <mt:Entry key="a">dddd</mt:Entry>
    <mt:Entry key="n">dddd</mt:Entry>
  </mt:VariableDataSet>
  <mt:VariableDataSet sequence="12344" timestamp="2019-01-01T20:00:00Z" count="0">
  UNAVAILABLE
  </mt:VariableDataSet>
  <mt:Variable sequence="12431" timestamp="2019-01-01T20:00:00Z">xaa="das\"dsasd" v="ad sa" d=add r={fdasfd\} dd} d='daf  d\'as' r="abc\"def" </mt:Variable>
  <mt:Variable sequence="12431" timestamp="2019-01-01T20:00:00Z"></mt:Variable>
  <mt:Variable sequence="12431" timestamp="2019-01-01T20:00:00Z">UNAVAILABLE</mt:Variable>
</mt:Samples>
